" Package manager
execute pathogen#infect()

" Have pathogen generate help files from the plugins installed
Helptags

" Set local vim files folder (`vimfiles` for Windows and `.vim` for everything
" else). If vim files are in another folder, this should already be set.
if !exists('g:localvim')
    if has('win32')
        let g:localvim="$HOME/vimfiles/"
    else
        let g:localvim="$HOME/.vim/"
    endif
endif

" Source out the other default settings (in the vimrc folder of this directory)
for f in split(glob(g:localvim . "/vimrc.d/**/*.vim"), '\n')
    exe 'source' f
endfor

