
" Set local vim files folder (`vimfiles` for Windows and `.vim` for everything
" else). If vim files are in another folder, this should already be set.
if !exists('g:localvim')
    if has('win32')
        let g:localvim="$HOME/vimfiles/"
    else
        let g:localvim="$HOME/.vim/"
    endif
endif

" Bootstrap pathogen (even in Vim 8 this is needed for generating helptags and
" pathogen is not loaded automatically).
runtime pack/foo/start/vim-pathogen/autoload/pathogen.vim

" If there is no native package manager (i.e., vim is not at least version
" v8.0), run Pathogen infect to load the rest of the plugins. (Recent versions
" of pathogen will know to look in pack/{}/start/ instead of the traditional
" bundle/ location.)
if v:version < 800
    execute pathogen#infect()
endif

" Have pathogen generate help files from the plugins installed
execute pathogen#helptags()

" Source out the other default settings (in the vimrc folder of this directory)
for f in split(glob(g:localvim . "/vimrc.d/**/*.vim"), '\n')
    exe 'source' f
endfor

